USE simplebankapidb;

CREATE TABLE BLOCKED_TOKENS (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `token` TEXT(7000) NOT NULL
);

CREATE EVENT `remove_blocked_token`
ON SCHEDULE EVERY 1 MINUTE 
DO DELETE FROM `BLOCKED_TOKENS` WHERE UNIX_TIMESTAMP(CURRENT_TIMESTAMP) - UNIX_TIMESTAMP(`created`) > 900;